// js/dragon-types.js — The six dragon lineages

const DRAGON_TYPES = {
  inferno: {
    id: 'inferno',
    name: 'Inferno',
    icon: '🔴',
    eggColor: '#E84040',
    trait: 'Hot-blooded & fierce',
    lore: 'Born from volcanic vents, the Inferno dragon craves heat above all else. Its scales glow with inner fire.',
    bonuses: { warmth: 15, energy: 5 },
    penalties: { bond: -5 },
    evolutionNames: ['Ember Egg','Cinder Sprite','Flame Drake','Pyro Drake','Inferno Wyrm','Volcanic Ancient'],
    evolutionIcons: ['🥚','🐣','🦎','🐉','🔥','☀️'],
    baseTheme: 'theme-fire',
    startAbility: { name: 'Ember Breath', icon: '🔥', power: 'Low', desc: 'A small but hot puff of fire.' },
  },
  glacial: {
    id: 'glacial',
    name: 'Glacial',
    icon: '🔵',
    eggColor: '#40C8E8',
    trait: 'Patient & ancient',
    lore: 'From the frozen peaks of the Skyspine Mountains. Its breath crystallizes the air itself.',
    bonuses: { nourish: 10, bond: 8 },
    penalties: { warmth: -10 },
    evolutionNames: ['Frost Egg','Ice Sprite','Crystal Drake','Glacier Drake','Glacial Wyrm','Eternal Frost'],
    evolutionIcons: ['🥚','🐣','❄️','🐉','🌊','🧊'],
    baseTheme: 'theme-frost',
    startAbility: { name: 'Frost Bite', icon: '❄️', power: 'Low', desc: 'Freezes foes with icy breath.' },
  },
  arcane: {
    id: 'arcane',
    name: 'Arcane',
    icon: '🟣',
    eggColor: '#9B5CF6',
    trait: 'Mysterious & wise',
    lore: 'Woven from pure magical energy. The Arcane dragon exists between realms, sensing things unseen.',
    bonuses: { bond: 15, energy: 8 },
    penalties: { nourish: -5 },
    evolutionNames: ['Mana Egg','Wisp Drake','Rune Sprite','Arcane Drake','Void Wyrm','Cosmic Ancient'],
    evolutionIcons: ['🥚','🐣','✨','🐉','🌀','🔮'],
    baseTheme: 'theme-arcane',
    startAbility: { name: 'Mind Link', icon: '🔮', power: 'Low', desc: 'Reads emotions and intentions.' },
  },
  storm: {
    id: 'storm',
    name: 'Storm',
    icon: '🟡',
    eggColor: '#FFD040',
    trait: 'Restless & powerful',
    lore: 'Born in the eye of a tempest. The Storm dragon crackles with lightning and rarely sits still.',
    bonuses: { energy: 20 },
    penalties: { bond: -8, nourish: -5 },
    evolutionNames: ['Thunder Egg','Static Sprite','Bolt Drake','Storm Drake','Thunder Wyrm','Sky God'],
    evolutionIcons: ['🥚','🐣','⚡','🐉','🌩️','🌪️'],
    baseTheme: 'theme-ember',
    startAbility: { name: 'Static Shock', icon: '⚡', power: 'Low', desc: 'A jolt of electricity.' },
  },
  verdant: {
    id: 'verdant',
    name: 'Verdant',
    icon: '🟢',
    eggColor: '#58E840',
    trait: 'Gentle & healing',
    lore: 'Grown from an ancient forest seed. The Verdant dragon carries the life-force of a thousand trees.',
    bonuses: { nourish: 20, bond: 5 },
    penalties: { energy: -5 },
    evolutionNames: ['Seed Egg','Sprout Drake','Thorn Drake','Grove Drake','Forest Wyrm','World Tree'],
    evolutionIcons: ['🥚','🐣','🌿','🐉','🌳','🌲'],
    baseTheme: 'theme-venom',
    startAbility: { name: 'Healing Aura', icon: '🌿', power: 'Low', desc: 'Radiates restorative energy.' },
  },
  void: {
    id: 'void',
    name: 'Void',
    icon: '⚫',
    eggColor: '#9E97C4',
    trait: 'Rare & enigmatic',
    lore: 'It should not exist. The Void dragon is a rift given form — neither fully here nor there.',
    bonuses: { bond: 10, energy: 10, warmth: 5, nourish: 5 },
    penalties: {},
    evolutionNames: ['Rift Egg','Shadow Sprite','Dusk Drake','Eclipse Drake','Void Wyrm','The Nameless'],
    evolutionIcons: ['🥚','🐣','🌑','🐉','🌌','♾️'],
    baseTheme: 'theme-void',
    startAbility: { name: 'Phase Shift', icon: '🌑', power: 'Medium', desc: 'Phases briefly out of reality.' },
  },
};
